from src.routes import auth
from src.routes import dashboard
from src.routes import items
from src.routes import sales
from src.routes import purchases
from src.routes import customers
from src.routes import vendors
from src.routes import branches
from src.routes import transfers
from src.routes import cash
from src.routes import reports
from src.routes import users